name = "terralogica"
compatibility_date = "2026-08-04"
pages_build_output_dir = "dist"

[vars]
ALLOWED_ORIGIN = "https://www.terralogica.mx"
NOTIFY_TO = "info@terralogica.mx"
NOTIFY_FROM = "Cotizador INVENTREES <onboarding@resend.dev>"

[[d1_databases]]
binding = "QUOTES_DB"
database_name = "terralogics_quotes"
database_id = "71179f8e-f79b-4fbe-b57e-467d7a722306"

[[r2_buckets]]
binding = "QUOTE_FILES"
bucket_name = "terralogics-quote-files"
